### PR TITLE
Upgrade to forge 3.0.0.Beta3 and Furance 2.23.0 and clean up slf4j

### PR DESCRIPTION
**Pull request by christian-posta**
collisions for running with the CLI

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
retest this please

**Comment by davsclaus** [comment]
darn @christian-posta this fails on the CI server. Does it pass on your system?

**Comment by christian-posta** [comment]
@davsclaus damn.. will rebase and see why it's not passing that test

**Comment by christian-posta** [comment]
@davsclaus that test fails for me locally on master.. does it work for anyone else?

**Comment by christian-posta** [comment]
@davsclaus scratch that... i needed to pass in some params and then it works just fine. digging in to why it doesn't with my patch!

**Comment by christian-posta** [comment]
will do this in two parts... first submit the Beta3 PR with https://github.com/fabric8io/fabric8-forge/pull/65

**Comment by davsclaus** [comment]
The beta3 upgrade is now in the master branch. Can you try to rebase and fix the merge conflicts so we can see if the rest of this PR can get merged.

**Pull request merged**
